// image
export const ADD_IMAGE_FROM_URL = 'ADD_IMAGE_FROM_URL';
export const ADD_IMAGE_FROM_JSON_FILE = 'ADD_IMAGE_FROM_JSON_FILE';
export const DELETE_IMAGE = 'DELETE_IMAGE';

// calc
export const SET_CALC_IS_CHANGED_FLAG = 'SET_GALERY_IS_CHANGED_FLAG';
export const SET_GALERY_WIDTH = 'SET_GALERY_WIDTH';
export const SET_CALC_RESULT = 'SET_CALC_RESULT';
